USE myEvents_db;

INSERT INTO Categoria (nome, descricao, id_categoria_pai) VALUES
('Meio Ambiente', 'Eventos relacionados à sustentabilidade, ecologia e preservação ambiental.', NULL),
('Artes', 'Exposições, apresentações culturais, shows e manifestações artísticas.', NULL),
('Medicina Veterinária', 'Palestras, workshops e eventos voltados para saúde e bem-estar animal.', NULL),
('Tecnologia da Informação', 'Eventos e conteúdos sobre computação, sistemas e inovação digital.', NULL),
('Medicina', 'Encontros e debates sobre saúde, avanços médicos e práticas clínicas.', NULL),
('Saúde e Bem-estar', 'Eventos focados em qualidade de vida, nutrição, atividade física e saúde mental.', NULL),
('Administração', 'Palestras, simpósios e treinamentos sobre gestão, liderança e negócios.', NULL),
('Educação', 'Eventos acadêmicos, pedagógicos e voltados para o aprendizado contínuo.', NULL),
('Ciências Sociais', 'Debates e congressos sobre sociedade, cultura, política e comportamento humano.', NULL),
('Jornalismo', 'Eventos e palestras sobre comunicação, mídia e informação.', NULL),
('Direito', 'Congressos, simpósios e palestras sobre legislação, justiça e advocacia.', NULL),
('Inovação', 'Eventos sobre criatividade, empreendedorismo e novas tendências de mercado.', NULL),
('Engenharia', 'Feiras, palestras e encontros sobre diferentes ramos da engenharia.', NULL),
('Gastronomia', 'Eventos sobre culinária, alimentação e cultura gastronômica.', NULL),
('Religião e Espiritualidade', 'Encontros e eventos sobre fé, espiritualidade e tradições religiosas.', NULL),
('Agricultura', 'Eventos sobre práticas agrícolas sustentáveis e inovações no campo.', 1),
('Pesca', 'Eventos e práticas voltadas à pesca sustentável e recursos hídricos.', 1),
('Cultura', 'Eventos culturais, tradições e expressões artísticas.', 2),
('Humanidades', 'Feiras e congressos voltados para filosofia, história e ciências humanas.', 2),
('Cinema Independente', 'Mostras, debates e exibições de produções audiovisuais independentes.', 2),
('Bem-estar Animal', 'Eventos e atividades sobre cuidado, proteção e direitos dos animais.', 3),
('Computação em Nuvem', 'Palestras e workshops sobre soluções e serviços em nuvem.', 4),
('Internet das Coisas (IoT)', 'Eventos sobre dispositivos conectados e aplicações inteligentes.', 4),
('Realidade Virtual', 'Encontros e experiências imersivas em realidade virtual.', 4),
('Medicina Preventiva', 'Eventos sobre prevenção de doenças e promoção da saúde.', 5),
('Psicologia Positiva', 'Encontros voltados ao desenvolvimento emocional e bem-estar psicológico.', 6),
('Dança', 'Espetáculos e oficinas de dança moderna e contemporânea.', 2),
('Desenvolvimento Pessoal', 'Palestras e eventos de autoconhecimento, habilidades e crescimento individual.', 6),
('Startups', 'Eventos e rodadas sobre negócios emergentes e inovação.', 7),
('E-commerce', 'Encontros e palestras sobre comércio digital e estratégias de vendas online.', 7),
('Empreendedorismo', 'Eventos para inspirar e capacitar novos empreendedores.', 7),
('Educação Financeira', 'Eventos sobre gestão de finanças pessoais e investimentos.', 8);

INSERT INTO Local (NomeLocal, capacidade, rua, numero, cidade, estado, cep) VALUES
('Itacimirim', 15000, 'Praia da Espera', NULL, 'Camaçari', 'BA', '42823-000'),
('R. Marapendi, 20', 150, 'R. Marapendi', 20, 'Rio de Janeiro', 'RJ', '21557-130'),
('Auditorio do CASS', 400, 'R. Afonso Cavalcanti,', 455, 'Rio de Janeiro', 'RJ', '20211-110'),
('EXPO MAG', 4500, 'R. Beatriz Larragoiti Lucas', NULL, 'Rio de Janeiro', 'RJ', ' 20211-175'),
('Jardim Primavera', 800, NULL, NULL, 'Duque de Caxias', 'RJ', '25231-630'),
('Morumbi Shopping', 1000, 'Av. Roque Petroni Júnior', 1089, 'São Paulo', 'SP', '04707-900'),
('CEMFA - Centro Municipal de Formação e Avaliação', 300, 'Av. Central', 1425, 'Caucaia ', 'CE', '61618-800'),
('Universidade Federal de Pelotas - Centro de Artes - Bloco 1', 500, 'R. Cel. Alberto Rosa', 62, 'Pelotas', 'RS', '96010-770'),
('Excellence Cursos', 100, 'Tv. Vila Yboty', 30, 'Nova Iguaçu', 'RJ', '26255-240'),
('Ipanguaçu', 5000, NULL, NULL, 'Ipanguaçu', 'RN', '59508-000'),
('Graúna Resort Hotel', 600, 'R. Vinte e Um', 3, 'Ouro Preto do Oeste', 'RO', '76920-000'),
('CREA - MA', 250, 'Av. dos Holandeses', 35, 'São Luís', 'MA', '65071-380'),
('Gran Tietê', 700, 'Av. 15 de Novembro', 170, 'Barra Bonita', 'SP', '17340-047'),
('São Paulo Expo', 60000, 'Rodovia dos Imigrantes, km 1,5', NULL, 'São Paulo', 'SP', '04329-900'),
('Riocentro', 90000, 'Av. Salvador Allende', 6555, 'Rio de Janeiro', 'RJ', '22783-127'),
('Centro de Convenções de Pernambuco', 20000, 'Av. Prof. Andrade Bezerra', NULL, 'Olinda', 'PE', '53110-680'),
('Expominas', 45000, 'Av. Amazonas', 6200, 'Belo Horizonte', 'MG', '30510-000'),
('Centro de Convenções Ulysses Guimarães', 9400, 'Sdc Eixo Monumental', NULL, 'Brasília', 'DF', '70070-350'),
('Classic Hall', 15000, 'Av. Agamenon Magalhães', NULL, 'Olinda', 'PE', '53110-710'),
('Jeunesse Arena', 18000, 'Av. Embaixador Abelardo Bueno', 3401, 'Rio de Janeiro', 'RJ', '22775-040'),
('Espaço Unimed', 8000, 'R. Tagipuru', 795, 'São Paulo', 'SP', '01156-000'),
('Centro de Convenções de Salvador', 20000, 'Av. Octávio Mangabeira', 5490, 'Salvador', 'BA', '41706-690'),
('Vibra São Paulo', 7000, 'Av. das Nações Unidas', 17955, 'São Paulo', 'SP', '04795-100'),
('Expo Unimed Curitiba', 14000, 'R. Prof. Pedro Viriato Parigot de Souza', 5300, 'Curitiba', 'PR', '81280-330'),
('Centro de Eventos FIERGS', 20000, 'Av. Assis Brasil', 8787, 'Porto Alegre', 'RS', '91140-001'),
('Arena Fonte Nova', 55000, 'Ladeira da Fonte das Pedras', NULL, 'Salvador', 'BA', '40050-565'),
('Anhembi Parque', 70000, 'Av. Olavo Fontoura', 1209, 'São Paulo', 'SP', '02012-021'),
('Vivo Rio', 4000, 'Av. Infante Dom Henrique', 85, 'Rio de Janeiro', 'RJ', '20021-140'),
('Arena MRV', 46000, 'Rua Cristina Maria de Assis', 202, 'Belo Horizonte', 'MG', '30855-450'),
('Centro de Eventos do Ceará', 30000, 'Av. Washington Soares', 999, 'Fortaleza', 'CE', '60811-905');

INSERT INTO TipoAtividade (nome, descricao) VALUES
('Palestra Magna', 'Apresentação principal do evento.'),
('Workshop Prático', 'Atividade com foco em aprendizado prático.'),
('Minicurso', 'Curso de curta duração sobre tema específico.'),
('Painel de Discussão', 'Debate com múltiplos especialistas.'),
('Mesa Redonda', 'Discussão mais informal sobre um tema.'),
('Sessão de Pôsteres', 'Apresentação de trabalhos acadêmicos.'),
('Hackathon', 'Maratona de programação.'),
('Sessão de Networking', 'Atividade para conectar participantes.'),
('Feira de Exposições', 'Exposição de produtos e serviços.'),
('Pitch de Startups', 'Apresentação rápida de startups.'),
('Sessão de Mentoria', 'Mentoria com especialistas da área.'),
('Palestra Técnica', 'Apresentação aprofundada em um tópico técnico.'),
('Apresentação de Case', 'Estudo de caso de sucesso.'),
('Lançamento de Produto', 'Apresentação de um novo produto.'),
('Debate Aberto', 'Debate com participação da plateia.'),
('Oficina Criativa', 'Atividade prática voltada para a criatividade.'),
('Competição', 'Competição entre participantes.'),
('Apresentação Cultural', 'Show, peça ou outra manifestação cultural.'),
('Sessão de Q&A', 'Sessão de perguntas e respostas.'),
('Tour Guiado', 'Visita guiada a um local específico.'),
('Encerramento', 'Cerimônia de encerramento do evento.'),
('Credenciamento', 'Registro e entrega de materiais.'),
('Coffee Break', 'Pausa para o café.'),
('Almoço', 'Intervalo para o almoço.'),
('Happy Hour', 'Confraternização ao final do dia.'),
('Treinamento Corporativo', 'Treinamento para empresas.'),
('Simpósio Acadêmico', 'Reunião de pesquisadores.'),
('Congresso', 'Grande evento de uma área específica.'),
('Seminário', 'Apresentação de um estudo ou pesquisa.'),
('Conferência', 'Evento com múltiplas palestras e trilhas.');

INSERT INTO Palestrante (nome, email, biografia, linkedin, lattes) VALUES
('Ana Silva', 'ana.silva@example.com', 'Doutora em Ciência da Computação pela USP, com mais de 15 anos de experiência em Inteligência Artificial e Machine Learning. É autora do livro "IA Descomplicada" e atualmente lidera a equipe de pesquisa em Processamento de Linguagem Natural em uma das maiores big techs do país.', 'linkedin.com/in/anasilva1', 'lattes.cnpq.br/1'),
('Bruno Costa', 'bruno.costa@example.com', 'Desenvolvedor Full Stack Sênior com uma década de experiência na criação de aplicações web escaláveis. Especialista em ecossistemas JavaScript (Node.js, React) e apaixonado por arquitetura de microsserviços e práticas DevOps. É um contribuidor ativo em projetos open-source.', 'linkedin.com/in/brunocosta2', 'lattes.cnpq.br/2'),
('Carla Dias', 'carla.dias@example.com', 'Médica cardiologista pelo InCor-HCFMUSP e pesquisadora com pós-doutorado em genética cardiovascular. Sua pesquisa foca no desenvolvimento de terapias inovadoras para doenças cardíacas hereditárias e já foi publicada em renomadas revistas científicas internacionais.', 'linkedin.com/in/carladias3', 'lattes.cnpq.br/3'),
('Daniel Barros', 'daniel.barros@example.com', 'Empreendedor serial e especialista em escalar negócios de tecnologia. Fundador da FinTech "Crescer Bank", que foi adquirida em uma das maiores transações do setor. Atualmente, atua como CEO em sua nova startup de SaaS e como mentor para novos empreendedores.', 'linkedin.com/in/danielbarros4', 'lattes.cnpq.br/4'),
('Eduarda Gomes', 'eduarda.gomes@example.com', 'Artista plástica e multimídia, cujas obras exploram a intersecção entre arte, tecnologia e natureza. Já realizou exposições individuais em São Paulo, Lisboa e Berlim, e foi vencedora do prestigiado Prêmio PIPA em 2023.', 'linkedin.com/in/eduardagomes5', 'lattes.cnpq.br/5'),
('Fábio Martins', 'fabio.martins@example.com', 'Doutor em Educação pela UNICAMP, com foco em metodologias ativas e tecnologia educacional. É consultor de políticas públicas para o ensino básico e autor de diversos artigos sobre a transformação digital na sala de aula e o futuro da aprendizagem.', 'linkedin.com/in/fabiomartins6', 'lattes.cnpq.br/6'),
('Gabriela Rocha', 'gabriela.rocha@example.com', 'Especialista em Segurança Cibernética com certificação CISSP e mais de 12 anos de experiência. Lidera a equipe de resposta a incidentes de uma consultoria global, ajudando empresas a protegerem seus dados contra ameaças avançadas e a se adequarem à LGPD.', 'linkedin.com/in/gabrielarocha7', 'lattes.cnpq.br/7'),
('Heitor Santos', 'heitor.santos@example.com', 'Nutricionista com especialização em nutrição esportiva e funcional. Acompanha atletas olímpicos e de alto rendimento, desenvolvendo estratégias alimentares para otimização de performance e recuperação. É colunista de saúde em portais de grande circulação.', 'linkedin.com/in/heitorsantos8', 'lattes.cnpq.br/8'),
('Isabela Souza', 'isabela.souza@example.com', 'Consultora de Marketing Digital e Branding com foco em marcas de consumo. Com MBA em Marketing pela FGV, é especialista em criar estratégias de conteúdo data-driven que geram engajamento e crescimento sustentável para seus clientes.', 'linkedin.com/in/isabelasouza9', 'lattes.cnpq.br/9'),
('João Teles', 'joao.teles@example.com', 'Fotógrafo documentarista e fotojornalista premiado internacionalmente. Seu trabalho, focado em questões sociais e ambientais na América Latina, já foi destaque em publicações como National Geographic e The Guardian.', 'linkedin.com/in/joaoteles10', 'lattes.cnpq.br/10'),
('Larissa Vieira', 'larissa.vieira@example.com', 'Mestre em Educação e Tecnologias Digitais, pioneira na implementação de programas de Ensino a Distância (EAD) em grandes instituições de ensino superior. Sua pesquisa atual investiga o uso de gamificação para aumentar o engajamento de alunos no ambiente online.', 'linkedin.com/in/larissavieira11', 'lattes.cnpq.br/11'),
('Marcos Xavier', 'marcos.xavier@example.com', 'Arquiteto de Soluções Cloud com múltiplas certificações (AWS, Azure, GCP). Possui vasta experiência em projetos de migração de infraestruturas legadas para a nuvem, com foco em otimização de custos, segurança e alta disponibilidade para o setor financeiro.', 'linkedin.com/in/marcosxavier12', 'lattes.cnpq.br/12'),
('Natália Andrade', 'natalia.andrade@example.com', 'Psicóloga clínica, com especialização em Terapia Cognitivo-Comportamental, e autora de dois best-sellers sobre saúde mental e ansiedade. É uma voz ativa na desmistificação de temas psicológicos nas redes sociais e na mídia.', 'linkedin.com/in/nataliaandrade13', 'lattes.cnpq.br/13'),
('Otávio Barbosa', 'otavio.barbosa@example.com', 'Investidor anjo e cofundador de uma das principais redes de investidores do Brasil. Com um portfólio de mais de 30 startups de tecnologia (SaaS, HealthTech, EdTech), foca em negócios com alto potencial de impacto e escalabilidade.', 'linkedin.com/in/otaviobarbosa14', 'lattes.cnpq.br/14'),
('Patrícia Campos', 'patricia.campos@example.com', 'Cineasta, roteirista e diretora de fotografia. Seus documentários e curtas-metragens, que abordam narrativas de resistência e identidade cultural, já foram selecionados e premiados em festivais como o de Gramado e o É Tudo Verdade.', 'linkedin.com/in/patriciacampos15', 'lattes.cnpq.br/15'),
('Rafael Duarte', 'rafael.duarte@example.com', 'Lead Game Designer com mais de 10 anos na indústria de jogos. Foi a mente criativa por trás do premiado jogo indie "Crônicas de Tordesilhas". É especialista em design de narrativas e mecânicas de jogabilidade para jogos de PC e console.', 'linkedin.com/in/rafaelduarte16', 'lattes.cnpq.br/16'),
('Sofia Esteves', 'sofia.esteves@example.com', 'Engenheira de Controle e Automação e Mestre em Engenharia Elétrica, com foco em Internet das Coisas (IoT). Desenvolve soluções de hardware e software para cidades inteligentes e indústria 4.0, e detém patentes na área de sensores conectados.', 'linkedin.com/in/sofiaesteves17', 'lattes.cnpq.br/17'),
('Tiago Freitas', 'tiago.freitas@example.com', 'Coach de carreira e liderança com certificação internacional (ICF). Com background em Recursos Humanos em multinacionais, hoje ajuda executivos e profissionais em transição de carreira a alcançarem seu máximo potencial através de metodologias focadas em autoconhecimento e planejamento estratégico.', 'linkedin.com/in/tiagofreitas18', 'lattes.cnpq.br/18'),
('Úrsula Henriques', 'ursula.henriques@example.com', 'Maestrina titular da Orquestra Filarmônica do Estado e pianista de renome. Com formação na Juilliard School, é conhecida por suas interpretações vibrantes e por seu trabalho na difusão da música clássica para novos públicos.', 'linkedin.com/in/ursulahenriques19', 'lattes.cnpq.br/19'),
('Vitor Lima', 'vitor.lima@example.com', 'Head de E-commerce e Transformação Digital em uma gigante do varejo. Foi responsável por liderar a estratégia omnichannel da empresa, resultando em um crescimento de mais de 300% nas vendas online nos últimos dois anos. Especialista em logística e experiência do cliente.', 'linkedin.com/in/vitorlima20', 'lattes.cnpq.br/20'),
('Wagner Matos', 'wagner.matos@example.com', 'Engenheiro de Software Sênior especialista em sistemas distribuídos de alta performance. Atualmente, trabalha na arquitetura de uma plataforma de streaming global, lidando com milhões de requisições por segundo. Defensor da cultura DevOps e de código limpo.', 'linkedin.com/in/wagnermatos21', 'lattes.cnpq.br/21'),
('Ximena Paiva', 'ximena.paiva@example.com', 'Primeira-bailarina do Theatro Municipal de São Paulo, aclamada pela crítica por sua técnica e expressividade. Já se apresentou como solista convidada em companhias de dança na Europa e na Ásia, e hoje também atua como coreógrafa.', 'linkedin.com/in/ximenapaiva22', 'lattes.cnpq.br/22'),
('Yasmin Queiroz', 'yasmin.queiroz@example.com', 'Planejadora e educadora financeira, criadora da plataforma "Meu Dinheiro, Minhas Regras". Descomplica o mundo dos investimentos para o público geral através de cursos online, workshops e um canal com milhares de seguidores, promovendo a independência financeira.', 'linkedin.com/in/yasminqueiroz23', 'lattes.cnpq.br/23'),
('Zeca Ribeiro', 'zeca.ribeiro@example.com', 'Desenvolvedor e pesquisador de tecnologias imersivas. Lidera um estúdio de desenvolvimento focado em criar experiências de Realidade Virtual (VR) e Aumentada (AR) para treinamento corporativo e educação. Palestrante frequente sobre o futuro do metaverso.', 'linkedin.com/in/zecaribeiro24', 'lattes.cnpq.br/24'),
('Amanda Sampaio', 'amanda.sampaio@example.com', 'Bioquímica e pesquisadora, com Doutorado em Biotecnologia pela Fiocruz. Sua pesquisa de ponta investiga o uso de biocompostos marinhos para o desenvolvimento de novos fármacos, com diversos artigos publicados em revistas de alto impacto.', 'linkedin.com/in/amandasampaio25', 'lattes.cnpq.br/25'),
('Bento Tavares', 'bento.tavares@example.com', 'Arquiteto de Soluções de TI Sênior, com ampla experiência em desenhar e implementar ecossistemas tecnológicos complexos para o setor bancário. É especialista em integrar novas tecnologias, como blockchain e IA, com sistemas legados de forma segura e eficiente.', 'linkedin.com/in/bentotavares26', 'lattes.cnpq.br/26'),
('Celina Uchoa', 'celina.uchoa@example.com', 'Fundadora e CEO da "Educa+", uma das EdTechs de maior crescimento na América Latina. Sua plataforma de aprendizado adaptativo, que usa IA para personalizar a jornada do estudante, já impactou milhões de alunos e a colocou na lista Forbes 30 Under 30.', 'linkedin.com/in/celinauchoa27', 'lattes.cnpq.br/27'),
('Davi Vasconcelos', 'davi.vasconcelos@example.com', 'Advogado especializado em Direito Digital e Propriedade Intelectual. É sócio de um escritório de advocacia focado em proteger os ativos de empresas de tecnologia, startups e criadores de conteúdo, atuando em casos de patentes de software e direitos autorais.', 'linkedin.com/in/davivasconcelos28', 'lattes.cnpq.br/28'),
('Elisa Wanderley', 'elisa.wanderley@example.com', 'Lead Product Designer (UX/UI) com um portfólio de projetos para aplicativos e plataformas digitais com milhões de usuários. É obcecada por criar produtos que sejam não apenas bonitos, mas também intuitivos, acessíveis e centrados nas necessidades humanas.', 'linkedin.com/in/elisawanderley29', 'lattes.cnpq.br/29'),
('Felipe Zampieri', 'felipe.zampieri@example.com', 'Cientista de Dados Sênior que utiliza modelos de machine learning para resolver problemas de negócio complexos. Com experiência no setor de varejo, é especialista em análise preditiva de comportamento do consumidor, otimização de estoque e sistemas de recomendação.', 'linkedin.com/in/felipezampieri30', 'lattes.cnpq.br/30');

INSERT INTO Especialidade (nome) VALUES
('Inteligência Artificial'),
('Machine Learning'),
('Desenvolvimento Full Stack'),
('DevOps'),
('Arquitetura de Software'),
('Cloud Computing'),
('Segurança Cibernética'),
('Internet das Coisas (IoT)'),
('Realidade Virtual'),
('Game Design'),
('Ciência de Dados'),
('UX/UI Design'),
('Liderança'),
('Marketing Digital'),
('E-commerce'),
('Educação Financeira'),
('Investimento Anjo'),
('Direito Digital'),
('Cardiologia'),
('Nutrição Esportiva'),
('Psicologia'),
('Pedagogia'),
('Educação a Distância (EAD)'),
('Artes Visuais'),
('Fotografia'),
('Dança Clássica'),
('Cinema'),
('Música Clássica'),
('Empreendedorismo'),
('Metodologias Ágeis');

INSERT INTO Evento (titulo, data_inicio, data_fim, carga_horaria, limite_participantes, expectiva_participantes, numero_participantes, numero_membros_comissao, id_categoria, email_duvidas) VALUES
('Simpósio Potiguar de Agroecologia – SIMPAGRO 2024', '2024-04-09', '2024-04-11', 30, 300, 250, 241, 3, 16, 'contato@simpagro.com.br'),
('Grupo de Coreografia', '2024-12-30', '2024-12-31', 10, 30, 30, 30, 1, 27, 'inscricao@coreografia.art.br'),
('Encontro medicinal', '2024-12-30', '2024-12-31', 5, 250, 200, 195, 15, 5, 'duvidas@encontromedicinal.com'),
('Réveillon Destino | 30/12', '2024-12-30', '2024-12-31', 10, 5000, 4500, 4678, 50, 18, 'contato@reveillondestino.com'),
('Culto de agradecimento a Deus!', '2024-12-31', '2024-12-31', 3, 200, 180, 185, 1, 15, 'contato@comunidadeagradecer.org'),
('Sistema Descentralizado de Pagamento - SDP - Turma 02', '2024-12-20', '2024-12-21', 6, 120, 100, 98, 3, 4, 'suporte.sdp@governo.com.br'),
('Novembro Azul - Projeto de Extensão LAMREDI', '2024-12-28', '2024-12-31', 6, 150, 130, 132, 2, 25, 'novembroazul@lamredi.org'),
('Formação 1 – O planejamento ressignificando práticas no chão da escola. Professores do 6º ao 9º ano de Língua Portuguesa', '2024-10-22', '2024-10-22', 8, 50, 45, 45, 1, 8, 'formacaoprofs@educa.com.br'),
('Programa Erês UEMG 2024', '2024-12-28', '2024-12-31', 3, 250, 230, 225, 2, 8, 'eres@uemg.edu.br'),
('I COLÓQUIO INTERNACIONAL Design e tecnologia da Aprendizagem (DTA) e Design de Experiências de Aprendizagem (DEA): Futuro e Tecnologia Educacional', '2024-11-04', '2024-11-09', 10, 400, 350, 330, 3, 8, 'coloquio.dta@evento.org'),
('Plano Nacional de Educação e Tecnologias: A Relevância de Políticas Públicas para o Desenvolvimento Educacional', '2024-09-26', '2024-09-26', 4, 150, 120, 115, 1, 8, 'pne.tecnologia@educacao.gov.br'),
('I Simpósio de Endodontia da LAEND - Tecnologia e Inovação em Endodontia.', '2024-05-04', '2024-05-04', 8, 300, 230, 235, 3, 5, 'simposio@laend.com.br'),
('Desenvolvimento Agropecuário no Cerrado: Conectando a Produtividade ao Respeito Ambiental', '2024-08-19', '2024-08-23', 10, 300, 280, 275, 2, 16, 'evento.cerrado@agro.com.br'),
('Rodada de Conversas AgRisk | Gestão Eficiente do Ciclo de Crédito em Empresas do Agronegócio', '2024-06-13', '2024-06-13', 2, 40, 30, 28, 1, 7, 'contato@agrisk.com'),
('IV SIMPÓSIO DE ENGENHARIAS, TECNOLOGIAS, ARQUITETURA & DESIGN E COMUNICAÇÃO & ARTES', '2024-06-17', '2024-06-21', 10, 800, 750, 742, 5, 13, 'simposio.eng@universidade.edu'),
('1º Simpósio Brasileiro de Engenharia da Nanotecnologia', '2024-09-30', '2024-10-04', 34, 250, 200, 190, 7, 13, 'simposio.nano@sben.org.br'),
('Webnar Tecnologia em saúde: Humanização no atendimento do paciente - o desafio com Dr Fernando Dalbão', '2024-03-27', '2024-03-27', 1, 500, 300, 312, 2, 5, 'webinar.humanizacao@saude.com'),
('V Seminário Internacional de Ensino da Arte: Territórios, Deslocamentos e Práticas Insurgentes', '2024-12-5', '2024-12-8', 15, 250, 200, 198, 3, 2, 'seminario.arte@internacional.org'),
('TÉCNICAS MIOFASCIAIS', '2024-12-31', '2024-12-31', 10, 60, 60, 60, 1, 6, 'curso@tecnicasmiofasciais.com'),
('Rosa Pela Vida - Prevenção do Câncer de Mama', '2024-12-28', '2024-12-31', 10, 400, 300, 295, 2, 25, 'rosapelavida@saude.org.br'),
('Workshop Sistema da informação, tecnologia, comunicação da informação e fluxo de dados na estrutura dos setores e nos processos internos', '2024-02-24', '2024-02-24', 1, 80, 70, 68, 1, 4, 'workshop.sistemas@ti.com.br'),
('Seminário Nacional de Catalogação e Tecnologia', '2024-09-24', '2024-09-26', 12, 350, 300, 290, 8, 4, 'contato@catalogacao.org.br'),
('5ª Jornada de Educação, Políticas e Tecnologias _ IFMS Campus Jardim', '2024-08-31', '2024-08-31', 5, 200, 180, 175, 2, 8, 'jornada.jardim@ifms.edu.br'),
('II CONGRESSO SOBRE DIREITO DIGITAL, MERCADO DIGITAL E NOVAS TECNOLOGias', '2024-11-12', '2024-11-14', 30, 500, 400, 410, 5, 11, 'congresso@direitodigital.adv.br'),
('I Congresso Nacional de Ciência e Tecnologia Aplicada à Saúde | II Simpósio de Ciência e Tecnologia Aplicada à Saúde', '2024-08-14', '2024-08-18', 40, 250, 200, 205, 4, 5, 'contato@cnctsaude.com.br'),
('2ª MOSTRA CIENTÍFICA DE EDUCAÇÃO E TECNOLOGIA', '2024-01-25', '2024-01-27', 16, 150, 130, 128, 1, 8, 'mostra@educatec.com.br'),
('AGROPROT', '2024-08-20', '2024-10-20', 10, 100, 80, 75, 1, 16, 'suporte@agroprot.com.br'),
('Caminhos da Produção Agroflorestal na Amazônia', '2024-07-02', '2024-07-10', 40, 60, 50, 48, 1, 16, 'agrofloresta.amazonia@evento.org'),
('Curso de Georreferenciamento (tecnologia) na Agronomia', '2024-06-05', '2024-06-08', 20, 40, 35, 35, 1, 16, 'curso.geo@agro.edu.br'),
('Palestra Alimentação Saudável', '2024-11-20', '2024-11-21', 2, 70, 50, 55, 1, 6, 'palestra@alimentacaosaudavel.com'),
('Tuberculose - Aula Expositiva', '2024-12-27', '2024-12-30', 10, 100, 90, 89, 4, 5, 'aula.tuberculose@medicina.edu'),
('II SEMANA DA ENGENHARIA AGRONÔMICA - FACULDADE GRAN TIETÊ - 2024', '2024-10-07', '2024-10-11', 20, 300, 250, 240, 3, 16, 'semana.agronomia@grantiete.edu.br'),
('Webinar sobre Inteligência Artificial na Saúde', '2024-02-15', '2024-02-15', 2, 500, 450, 435, 2, 5, 'webinar.ia@saudedigital.com'),
('Curso Online de Gestão de Projetos Ágeis', '2024-03-04', '2024-03-18', 20, 100, 80, 78, 3, 7, 'suporte@cursogpa.com'),
('Conferência Virtual de Inovação em Fintechs', '2024-03-22', '2024-03-24', 15, 1500, 1000, 1105, 10, 7, 'contato@fintechconf.com'),
('Seminário Online de Direito Ambiental', '2024-04-08', '2024-04-09', 8, 200, 150, 145, 4, 11, 'seminario@direitoambiental.org'),
('Workshop de Escrita Criativa Online', '2024-04-20', '2024-04-20', 4, 50, 50, 50, 1, 2, 'inscricao@escritacriativa.art.br'),
('Palestra Online: O Futuro da Energia Renovável', '2024-05-04', '2024-05-04', 2, 500, 300, 320, 2, 13, 'palestra@energiafuturo.com'),
('Aula Magna Digital de Astrofísica', '2024-05-17', '2024-05-17', 3, 1000, 800, 780, 1, 8, 'aulamagna.astro@uni.edu.br'),
('Simpósio Virtual sobre Segurança Cibernética', '2024-06-10', '2024-06-12', 12, 400, 350, 345, 6, 4, 'contato@cybersecsimposio.com.br'),
('Live com Autores de Literatura Fantástica', '2024-08-28', '2024-08-28', 2, 2000, 1500, 1650, 2, 2, 'live@autoresfantasticos.com'),
('Curso Intensivo de Marketing Digital para Iniciantes', '2024-09-02', '2024-09-30', 40, 150, 120, 118, 3, 7, 'suporte@mktdigitalcurso.com'),
('Encontro Virtual de Fisioterapia Esportiva', '2024-10-11', '2024-10-12', 6, 250, 200, 210, 4, 6, 'contato@fisioesportiva.com.br'),
('Feira de Gastronomia Regional de Pernambuco', '2024-11-22', '2024-11-24', 24, 2000, 1800, 1850, 15, 14, 'feira.pe@gastronomia.com.br'),
('Congresso Brasileiro de Cardiologia', '2024-11-12', '2024-11-15', 32, 5000, 4500, 4450, 25, 5, 'inscricao@sbc-cardio.org.br'),
('Exposição de Arte Moderna "Novas Formas"', '2025-01-15', '2025-03-15', 100, 500, 400, 420, 5, 2, 'visitas@expoartemoderna.mus.br'),
('Festival de Rock Independente do Nordeste', '2025-01-25', '2025-01-26', 16, 10000, 9000, 8850, 30, 18, 'contato@rockindependente-ne.com'),
('Hackathon de Desenvolvimento de Apps Sociais', '2025-02-07', '2025-02-09', 48, 100, 100, 99, 8, 4, 'hackathon.social@devsummit.com'),
('Semana de Arquitetura e Urbanismo', '2025-02-17', '2025-02-21', 40, 300, 280, 270, 7, 13, 'secretaria@semana-arqurb.com'),
('Campeonato Regional de Voleibol', '2025-03-14', '2025-03-16', 20, 500, 500, 498, 12, 6, 'campeonato@voleiregional.esp.br'),
('Feira de Adoção de Animais', '2025-03-22', '2025-03-22', 8, 500, 400, 415, 5, 21, 'adocao@amigopet.org'),
('Retiro de Yoga e Meditação na Chapada', '2025-04-04', '2025-04-06', 18, 40, 40, 40, 3, 6, 'paz@retirochapada.com'),
('Congresso de Engenharia de Produção', '2025-04-22', '2025-04-25', 30, 800, 700, 680, 10, 13, 'contato@congressoproducao.com.br'),
('Oficina de Teatro para Crianças', '2025-05-03', '2025-05-31', 16, 25, 25, 24, 2, 2, 'oficina.kids@teatroinfantil.com'),
('Encontro Nacional de Estudantes de História', '2025-05-12', '2025-05-16', 40, 1200, 1000, 950, 9, 8, 'contato@eneh2025.com.br'),
('Maratona de Recife 2025', '2025-06-01', '2025-06-01', 10, 15000, 13000, 13210, 40, 6, 'corrida@maratonadorecife.com.br'),
('Simpósio de Agronegócio Sustentável', '2025-06-09', '2025-06-12', 25, 600, 550, 530, 11, 16, 'contato@agrosustentavel.com'),
('Show de Comédia Stand-Up com Artistas Locais', '2025-06-14', '2025-06-14', 3, 400, 400, 400, 4, 18, 'risada@comedialocal.com'),
('Conferência Estadual de Educação Inclusiva', '2025-06-23', '2025-06-25', 20, 500, 400, 380, 8, 8, 'contato@educacaoinclusiva-pe.gov.br'),
('Bazar Beneficente de Natal', '2024-12-07', '2024-12-08', 12, 1000, 850, 870, 20, 15, 'ajuda@bazardenatal.org');

INSERT INTO EventoOnline (id_evento, url_evento, aplicativoTrasmissao) VALUES
(7, 'https://myevents.com/novembro-azul-projeto-extensao-lamredi', 'Zoom'),
(9, 'https://myevents.com/programa-eres-uemg-2024', 'YouTube'),
(10, 'https://myevents.com/coloquio-internacional-design-tecnologia-aprendizagem', 'Google Meet'),
(11, 'https://myevents.com/plano-nacional-educacao-tecnologias', 'Vimeo'),
(12, 'https://myevents.com/simposio-endodontia-laend-tecnologia-inovacao', 'Zoom'),
(13, 'https://myevents.com/desenvolvimento-agropecuario-cerrado', 'YouTube'),
(14, 'https://myevents.com/rodada-de-conversas-agrisk-gestao-credito', 'Google Meet'),
(15, 'https://myevents.com/iv-simposio-engenharias-tecnologias-design-artes', 'Vimeo'),
(16, 'https://myevents.com/1-simposio-brasileiro-engenharia-nanotecnologia', 'Zoom'),
(17, 'https://myevents.com/webnar-tecnologia-em-saude-humanizacao-atendimento', 'YouTube'),
(20, 'https://myevents.com/rosa-pela-vida-prevencao-cancer-de-mama', 'Google Meet'),
(21, 'https://myevents.com/workshop-sistema-informacao-tecnologia', 'Vimeo'),
(22, 'https://myevents.com/seminario-nacional-catalogacao-tecnologia', 'Zoom'),
(23, 'https://myevents.com/5-jornada-educacao-politicas-tecnologias-ifms-jardim', 'YouTube'),
(24, 'https://myevents.com/ii-congresso-direito-digital-mercado-novas-tecnologias', 'Google Meet'),
(25, 'https://myevents.com/congresso-nacional-ciencia-tecnologia-aplicada-saude', 'Vimeo'),
(26, 'https://myevents.com/2-mostra-cientifica-educacao-tecnologia', 'Zoom'),
(27, 'https://myevents.com/agroprot-2024', 'YouTube'),
(31, 'https://myevents.com/tuberculose-aula-expositiva', 'Google Meet'),
(33, 'https://myevents.com/webinar-ia-saude-2026', 'Zoom'),
(34, 'https://myevents.com/curso-gestao-projetos-ageis', 'Google Meet'),
(35, 'https://myevents.com/conferencia-fintechs-2026', 'Microsoft Teams'),
(36, 'https://myevents.com/seminario-direito-ambiental', 'YouTube'),
(37, 'https://myevents.com/workshop-escrita-criativa', 'Zoom'),
(38, 'https://myevents.com/palestra-energia-renovavel', 'Vimeo'),
(39, 'https://myevents.com/aula-magna-astrofisica', 'YouTube'),
(40, 'https://myevents.com/simposio-ciberseguranca-2026', 'Google Meet'),
(41, 'https://myevents.com/live-autores-fantasticos', 'YouTube'),
(42, 'https://myevents.com/curso-marketing-digital-iniciantes', 'Zoom'),
(43, 'https://myevents.com/encontro-fisioterapia-esportiva', 'Microsoft Teams');

INSERT INTO EventoPresencial (id_evento, id_local) VALUES
(4, 1), 
(5, 2),
(6, 3), 
(30, 4), 
(2, 5), 
(3, 6), 
(8, 7), 
(18, 8), 
(19, 9), 
(1, 10), 
(28, 11),
(29, 12), 
(32, 13),
(44, 14),
(45, 15),
(46, 16),
(47, 17),
(48, 18),
(49, 19),
(50, 20),
(51, 21),
(52, 22),
(53, 23),
(54, 24),
(55, 25),
(56, 26),
(57, 27),
(58, 28),
(59, 29),
(60, 30);

INSERT INTO Atividade (titulo, descricao, limite_vagas, link_transmissao_atividade, carga_horaria, id_evento, id_tipoAtividade) VALUES
('Palestra de Abertura: O Futuro da Agroecologia no Nordeste', 'Abertura oficial do SIMPAGRO com a presença de autoridades e especialistas renomados na área.', 300, NULL, 2, 1, 1),
('Minicurso: Manejo Sustentável de Pragas e Doenças', 'Curso prático sobre técnicas de controle biológico e defensivos naturais para pequenas e médias propriedades.', 50, NULL, 8, 1, 3),
('Painel: Políticas Públicas para a Agricultura Familiar', 'Debate sobre os desafios e oportunidades das políticas de incentivo à produção agroecológica familiar.', 150, NULL, 3, 1, 4),
('Show Principal com a Banda Sol Nascente', 'Apresentação da banda principal da noite, tocando os maiores sucessos do axé e pop rock nacional.', 5000, NULL, 4, 4, 18),
('DJ Set Eletrônico - Pista Amanhecer', 'DJ convidado agitando a pista com o melhor da música eletrônica até o sol raiar.', 5000, NULL, 5, 4, 18),
('Keynote Internacional: A Revolução do Ensino Híbrido', 'Palestra magna com Dr. Alistair Finch sobre as tendências globais em tecnologia educacional e design de aprendizagem.', 400, 'https://youtube.com/live/coloquioDTA1', 2, 10, 1),
('Workshop: Ferramentas de Gamificação para Engajamento de Alunos', 'Sessão prática para educadores aprenderem a criar e aplicar elementos de jogos em suas aulas.', 60, 'https://myevents.com/coloquio-internacional-design-tecnologia-aprendizagem', 4, 10, 2),
('Apresentação de Artigos Científicos - Eixo 1', 'Apresentação de pesquisas selecionadas sobre Experiências de Aprendizagem Imersivas (Realidade Virtual e Aumentada).', 200, 'https://myevents.com/coloquio-internacional-design-tecnologia-aprendizagem', 3, 10, 29),
('Palestra: Inovações em Instrumentação Rotatória e Reciprocante', 'Discussão aprofundada sobre as mais recentes tecnologias em instrumentação para tratamento de canal.', 300, 'https://myevents.com/simposio-endodontia-laend-tecnologia-inovacao', 2, 12, 12),
('Hands-on: Uso de Localizadores Apicais Eletrônicos', 'Treinamento prático com modelos para o uso correto e eficiente de localizadores apicais de última geração.', 40, 'https://myevents.com/simposio-endodontia-laend-tecnologia-inovacao', 3, 12, 2),
('Palestra Magna de Abertura: Cidades Inteligentes e Sustentabilidade', 'Abertura do simpósio com foco no papel da engenharia e arquitetura na construção de futuros urbanos sustentáveis.', 800, 'https://zoom.us/j/12345IVSimposio', 2, 15, 1),
('Concurso de Pontes de Palito de Picolé', 'Tradicional competição entre estudantes de engenharia civil para testar projetos estruturais em escala.', 100, 'https://myevents.com/iv-simposio-engenharias-tecnologias-design-artes', 8, 15, 17),
('Minicurso de Design Thinking Aplicado a Projetos', 'Curso intensivo sobre a metodologia do Design Thinking para solução de problemas complexos em projetos.', 50, 'https://myevents.com/iv-simposio-engenharias-tecnologias-design-artes', 8, 15, 3),
('Webinar: Humanização no Atendimento ao Paciente', 'Apresentação online com Dr. Fernando Dalbão sobre os desafios e estratégias para um atendimento mais humano na era digital.', 500, 'https://meet.google.com/webinar-saude', 1, 17, 12),
('Painel: A LGPD e seus Impactos no Mercado Digital', 'Debate com juristas e especialistas em proteção de dados sobre os desafios da aplicação da LGPD.', 500, 'https://youtube.com/live/direito-digital-lgpd', 3, 24, 4),
('Workshop: Elaboração de Contratos para Startups de Tecnologia', 'Atividade prática voltada para advogados sobre cláusulas essenciais em contratos de software e serviços digitais.', 80, 'https://myevents.com/ii-congresso-direito-digital-mercado-novas-tecnologias', 4, 24, 2),
('Palestra de Encerramento: O Futuro da IA e a Ética Jurídica', 'Reflexões sobre os dilemas éticos e a regulamentação necessária para o avanço da IA no campo do direito.', 500, 'https://myevents.com/ii-congresso-direito-digital-mercado-novas-tecnologias', 2, 24, 21),
('Mesa Redonda: Telemedicina e o Acesso à Saúde no Brasil', 'Discussão mais informal sobre os avanços, regulamentação e desafios da telemedicina.', 250, 'https://myevents.com/congresso-nacional-ciencia-tecnologia-aplicada-saude', 3, 25, 5),
('Sessão de Pôsteres Científicos', 'Exposição e avaliação de trabalhos científicos desenvolvidos por pesquisadores e estudantes de todo o país.', 250, 'https://myevents.com/congresso-nacional-ciencia-tecnologia-aplicada-saude', 4, 25, 6),
('Palestra: Agricultura de Precisão e o Uso de Drones', 'Apresentação sobre como a tecnologia de drones está otimizando o monitoramento e a aplicação de insumos.', 300, NULL, 2, 32, 12),
('Dia de Campo: Visita Técnica a Fazenda Experimental', 'Atividade externa para observação de práticas de manejo integrado e novas cultivares.', 60, NULL, 8, 32, 20),
('Painel de Abertura: O Open Banking e a Transformação do Mercado Financeiro', 'Debate sobre o impacto do Open Banking no Brasil, com líderes de grandes bancos e fintechs.', 1500, 'https://fintechconf.com/live/abertura', 2, 35, 4),
('Rodada de Pitch com Startups', 'Apresentação de novas startups do setor financeiro para um painel de investidores-anjo.', 200, 'https://fintechconf.com/live/pitch', 3, 35, 10),
('Palestra: Engenharia Social - Como Proteger sua Empresa', 'Apresentação focada nas principais técnicas de engenharia social usadas por hackers.', 400, 'https://cybersecsimposio.com/palestra1', 2, 40, 12),
('Workshop Técnico: Análise de Malware em Ambientes Controlados', 'Sessão prática para analistas de segurança sobre técnicas de análise de artefatos maliciosos.', 50, 'https://cybersecsimposio.com/workshop-malware', 4, 40, 2),
('Aula Show: Segredos do Bolo de Rolo', 'Chef renomado ensina ao vivo os segredos para preparar o autêntico Bolo de Rolo.', 100, NULL, 2, 44, 18),
('Degustação de Queijos e Cachaças Artesanais', 'Espaço dedicado à degustação e harmonização de produtos de fabricação artesanal do estado.', 150, NULL, 3, 44, 9),
('Concurso "O Melhor Sabor da Feira"', 'Competição onde o público e um júri técnico elegem o melhor prato ou produto da feira.', 2000, NULL, 6, 44, 17),
('Simpósio: Novas Fronteiras no Tratamento da Hipertensão Arterial', 'Apresentação de novos medicamentos e abordagens terapêuticas para o controle da hipertensão.', 500, NULL, 3, 45, 27),
('Curso de Eletrocardiograma para o Clínico', 'Curso intensivo de atualização em interpretação de ECG, voltado para médicos não especialistas.', 150, NULL, 8, 45, 3),
('Sessão de Temas Livres Orais', 'Apresentação dos melhores trabalhos de pesquisa submetidos ao congresso, com premiação.', 1000, NULL, 4, 45, 29),
('Cerimônia de Encerramento e Premiação', 'Conclusão do evento, com a entrega de prêmios e homenagem a cardiologistas de destaque.', 5000, NULL, 2, 45, 21),
('Show da Banda "Cactos Elétricos"', 'Apresentação da banda headliner da primeira noite do festival.', 10000, NULL, 2, 47, 18),
('Palco "Som do Agreste" - Apresentação de Novas Bandas', 'Espaço dedicado a bandas emergentes da cena do rock nordestino.', 2000, NULL, 6, 47, 18),
('Batalha de Bandas', 'Competição para revelar a nova promessa do rock independente, com votação do público e júri.', 3000, NULL, 4, 47, 17),
('Maratona de Programação 48h', 'Evento principal onde as equipes terão 48 horas para desenvolver um aplicativo com impacto social.', 100, NULL, 48, 48, 7),
('Sessão de Mentoria com Especialistas do Mercado', 'Momentos durante o hackathon onde equipes podem tirar dúvidas com desenvolvedores seniores e especialistas em UX/UI.', 100, NULL, 6, 48, 11),
('Oficina de Maquetes com Impressão 3D', 'Workshop prático sobre o uso de impressão 3D na criação de maquetes arquitetônicas.', 30, NULL, 8, 49, 16),
('Palestra: Urbanismo Tático e a Requalificação de Espaços Públicos', 'Discussão sobre intervenções urbanas de baixo custo e alto impacto para melhorar a vida nas cidades.', 300, NULL, 2, 49, 12),
('Exposição de Projetos de Conclusão de Curso', 'Mostra dos melhores trabalhos de conclusão de curso dos formandos em Arquitetura e Urbanismo.', 300, NULL, 10, 49, 9),
('Palestra: Indústria 4.0 e a Otimização de Processos', 'Apresentação sobre como os conceitos da Indústria 4.0 estão revolucionando a engenharia de produção.', 800, NULL, 2, 53, 12),
('Minicurso: Lean Manufacturing na Prática', 'Curso sobre os princípios do Lean para a redução de desperdícios e aumento da eficiência em produção.', 60, NULL, 8, 53, 3),
('Visita Técnica à Fábrica da "Indústria ABC"', 'Oportunidade de conhecer na prática os processos de produção de uma grande indústria da região.', 40, NULL, 4, 53, 20),
('Mesa de Abertura: A História e os Desafios do Tempo Presente', 'Debate com historiadores renomados sobre o papel do conhecimento histórico na atualidade.', 1200, NULL, 3, 55, 5),
('GT 05: Gênero, Raça e Classe na História do Brasil', 'Sessão do Grupo de Trabalho para apresentação e debate de pesquisas de estudantes sobre estas temáticas.', 100, NULL, 4, 55, 29),
('Sarau Histórico e Político', 'Espaço aberto para manifestações artísticas dos participantes, como música, poesia e performance.', 400, NULL, 3, 55, 18),
('Entrega dos Kits dos Atletas', 'Período e local definidos para que os corredores inscritos retirem seus kits de participação.', 15000, NULL, 8, 56, 22),
('Corrida Principal - 42km', 'A prova principal da maratona, com largada no Marco Zero e percurso pelos pontos turísticos do Recife.', 3000, NULL, 6, 56, 17),
('Leilão Silencioso de Obras de Arte', 'Leilão de peças doadas por artistas locais, com renda revertida para instituições de caridade.', 200, NULL, 5, 60, 17),
('Apresentação do Coral Infantil "Vozes de Esperança"', 'Performance musical com crianças da comunidade, trazendo canções natalinas para os visitantes do bazar.', 500, NULL, 1, 60, 18);

INSERT INTO Palestrante_Especialidade (id_palestrante, id_especialidade) VALUES
(1, 1),
(1, 2),
(2, 3),
(2, 4),
(2, 5),
(3, 19),
(4, 29),
(5, 24),
(6, 22),
(7, 7),
(8, 20),
(9, 14),
(10, 25),
(11, 23),
(11, 22),
(12, 6),
(12, 5),
(13, 21),
(14, 17),
(14, 29),
(15, 27),
(16, 10),
(17, 8),
(18, 13),
(19, 28),
(20, 15),
(20, 14),
(21, 5),
(21, 4),
(22, 26),
(23, 16),
(24, 9),
(26, 5),
(26, 1),
(27, 29),
(27, 1),
(27, 23),
(28, 18),
(29, 12),
(30, 11),
(30, 2);

INSERT INTO Apresentacao (id_palestrante, id_atividade) VALUES
(1, 1),
(27, 6),
(17, 11),
(28, 17),
(26, 22),
(1, 40),
(6, 2),
(11, 7),
(29, 13),
(28, 16),
(21, 24),
(24, 37),
(30, 41),
(4, 3),
(7, 15),
(28, 15),
(3, 18),
(26, 23),
(14, 23),
(6, 43),
(13, 29),
(18, 29),
(24, 8),
(7, 24),
(16, 25),
(19, 26),
(3, 28),
(8, 29),
(13, 30),
(19, 31),
(22, 32),
(5, 33),
(15, 34),
(2, 35),
(21, 35),
(17, 38),
(12, 39),
(25, 20),
(20, 19),
(9, 21),
(23, 27),
(10, 44),
(8, 45),
(5, 46),
(19, 47);

INSERT INTO MaterialDeApoio (tipo_arquivo, url_do_arquivo, id_palestrante, id_atividade) VALUES
('PDF', 'https://storage.evento.com/materiais/1_1_anasiva_abertura.pdf', 1, 1),
('PPTX', 'https://storage.evento.com/materiais/6_27_celinauchoa_ensino_hibrido.pptx', 27, 6),
('PDF', 'https://storage.evento.com/materiais/11_17_sofiaesteves_cidades_inteligentes.pdf', 17, 11),
('PDF', 'https://storage.evento.com/materiais/17_28_davivasconcelos_etica_juridica.pdf', 28, 17),
('DOCX', 'https://storage.evento.com/materiais/22_26_bentotavares_openbanking_resumo.docx', 26, 22),
('PPTX', 'https://storage.evento.com/materiais/40_1_anasiva_industria40.pptx', 1, 40),
('ZIP', 'https://storage.evento.com/materiais/2_6_fabiomartins_manejo_pragas.zip', 6, 2),
('PDF', 'https://storage.evento.com/materiais/7_11_larissavieira_gamificacao_apostila.pdf', 11, 7),
('Link Externo', 'https://miro.com/board/asdf123_design_thinking_ew', 29, 13),
('DOCX', 'https://storage.evento.com/materiais/16_28_davivasconcelos_contratos_modelos.docx', 28, 16),
('ZIP', 'https://storage.evento.com/materiais/25_21_wagnermatos_analise_malware.zip', 21, 24),
('ZIP', 'https://storage.evento.com/materiais/37_24_zecaribeiro_modelos_3d.zip', 24, 37),
('PDF', 'https://storage.evento.com/materiais/41_30_felipezampieri_lean_manufacturing.pdf', 30, 41),
('PPTX', 'https://storage.evento.com/materiais/15_7_gabrielarocha_lgpd_impactos.pptx', 7, 15),
('PPTX', 'https://storage.evento.com/materiais/15_28_davivasconcelos_lgpd_juridico.pptx', 28, 15),
('Link Externo', 'https://pubmed.ncbi.nlm.nih.gov/12345678/', 3, 18),
('PDF', 'https://storage.evento.com/materiais/23_14_otaviobarbosa_guia_pitch.pdf', 14, 23),
('PDF', 'https://storage.evento.com/materiais/29_13_nataliaandrade_worksheet_mentoria.pdf', 13, 29),
('DOCX', 'https://storage.evento.com/materiais/29_18_tiagofreitas_plano_carreira.docx', 18, 29),
('PDF', 'https://storage.evento.com/materiais/8_24_zecaribeiro_artigo_vr_ar.pdf', 24, 8),
('PPTX', 'https://storage.evento.com/materiais/24_7_gabrielarocha_engenharia_social.pptx', 7, 24),
('PDF', 'https://storage.evento.com/materiais/28_3_carladias_hipertensao_tratamento.pdf', 3, 28),
('PDF', 'https://storage.evento.com/materiais/29_8_heitorsantos_curso_ecg.pdf', 8, 29),
('PPTX', 'https://storage.evento.com/materiais/30_13_nataliaandrade_pesquisa_psicologia.pptx', 13, 30),
('Link Externo', 'https://github.com/brunocosta/hackathon-boilerplate', 2, 35),
('PDF', 'https://storage.evento.com/materiais/35_21_wagnermatos_api_docs.pdf', 21, 35),
('PDF', 'https://storage.evento.com/materiais/38_17_sofiaesteves_urbanismo_tatico.pdf', 17, 38),
('PDF', 'https://storage.evento.com/materiais/20_25_amandasampaio_roteiro_visita.pdf', 25, 20),
('PPTX', 'https://storage.evento.com/materiais/19_20_vitorlima_agricultura_precisao.pptx', 20, 19),
('PPTX', 'https://storage.evento.com/materiais/21_9_isabelasouza_openbanking_mkt.pptx', 9, 21),
('DOCX', 'https://storage.evento.com/materiais/43_6_fabiomartins_gt05_leituras.docx', 6, 43),
('PDF', 'https://storage.evento.com/materiais/23_26_bentotavares_guia_startup_ti.pdf', 26, 23),
('Link Externo', 'https://figma.com/proto/12345/design_thinking_ew', 29, 13),
('ZIP', 'https://storage.evento.com/materiais/41_30_felipezampieri_datasets.zip', 30, 41),
('PDF', 'https://storage.evento.com/materiais/2_6_fabiomartins_manejo_artigos.pdf', 6, 2);